# The Docker image that will be used to build your app
image: node:19
# Functions that should be executed before the build script is run
before_script:
    - echo "NODE_ENV=production" >> .env
    - echo "PROJECT_URL=/official/op/avatar/" >> .env
    - yarn install
    - npx update-browserslist-db@latest
    - yarn run build

pages:
  script:
    - rm -rf public
    - mkdir public
    - cp -r dist/* public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  only:
    - master
